
import { AtsPlatform } from './types';

export const INITIAL_COMPANIES = [
  // GREENHOUSE - BIG TECH & HIGH GROWTH
  { name: "Airbnb", identifier: "airbnb", platform: AtsPlatform.GREENHOUSE },
  { name: "Uber", identifier: "uber", platform: AtsPlatform.GREENHOUSE },
  { name: "Stripe", identifier: "stripe", platform: AtsPlatform.GREENHOUSE },
  { name: "Twitch", identifier: "twitch", platform: AtsPlatform.GREENHOUSE },
  { name: "GitLab", identifier: "gitlab", platform: AtsPlatform.GREENHOUSE },
  { name: "DoorDash", identifier: "doordash", platform: AtsPlatform.GREENHOUSE },
  { name: "Pinterest", identifier: "pinterest", platform: AtsPlatform.GREENHOUSE },
  { name: "Robinhood", identifier: "robinhood", platform: AtsPlatform.GREENHOUSE },
  { name: "Coinbase", identifier: "coinbase", platform: AtsPlatform.GREENHOUSE },
  { name: "Dropbox", identifier: "dropbox", platform: AtsPlatform.GREENHOUSE },
  { name: "Discord", identifier: "discord", platform: AtsPlatform.GREENHOUSE },
  { name: "Instacart", identifier: "instacart", platform: AtsPlatform.GREENHOUSE },
  { name: "Peloton", identifier: "peloton", platform: AtsPlatform.GREENHOUSE },
  { name: "Roku", identifier: "roku", platform: AtsPlatform.GREENHOUSE },
  { name: "Wayfair", identifier: "wayfair", platform: AtsPlatform.GREENHOUSE },
  { name: "SoFi", identifier: "sofi", platform: AtsPlatform.GREENHOUSE },
  { name: "Okta", identifier: "okta", platform: AtsPlatform.GREENHOUSE },
  { name: "Brex", identifier: "brex", platform: AtsPlatform.GREENHOUSE },
  { name: "Plaid", identifier: "plaid", platform: AtsPlatform.GREENHOUSE },
  { name: "Databricks", identifier: "databricks", platform: AtsPlatform.GREENHOUSE },
  { name: "Gusto", identifier: "gusto", platform: AtsPlatform.GREENHOUSE },
  { name: "HashiCorp", identifier: "hashicorp", platform: AtsPlatform.GREENHOUSE },
  { name: "Twilio", identifier: "twilio", platform: AtsPlatform.GREENHOUSE },
  { name: "Cloudflare", identifier: "cloudflare", platform: AtsPlatform.GREENHOUSE },
  { name: "Asana", identifier: "asana", platform: AtsPlatform.GREENHOUSE },
  { name: "Duolingo", identifier: "duolingo", platform: AtsPlatform.GREENHOUSE },
  { name: "Vercel", identifier: "vercel", platform: AtsPlatform.GREENHOUSE },
  { name: "Reddit", identifier: "reddit", platform: AtsPlatform.GREENHOUSE },
  { name: "Lyft", identifier: "lyft", platform: AtsPlatform.GREENHOUSE },
  { name: "Udemy", identifier: "udemy", platform: AtsPlatform.GREENHOUSE },
  { name: "Datadog", identifier: "datadoghq", platform: AtsPlatform.GREENHOUSE },
  { name: "Zoom", identifier: "zoom", platform: AtsPlatform.GREENHOUSE },
  { name: "Square", identifier: "squareup", platform: AtsPlatform.GREENHOUSE },
  { name: "ClickUp", identifier: "clickup", platform: AtsPlatform.GREENHOUSE },
  { name: "Postman", identifier: "postman", platform: AtsPlatform.GREENHOUSE },

  // GREENHOUSE - INDIAN UNICORNS
  { name: "Zomato", identifier: "zomato", platform: AtsPlatform.GREENHOUSE },
  { name: "Swiggy", identifier: "swiggy", platform: AtsPlatform.GREENHOUSE },
  { name: "PhonePe", identifier: "phonepe", platform: AtsPlatform.GREENHOUSE },
  { name: "Razorpay", identifier: "razorpay", platform: AtsPlatform.GREENHOUSE },
  { name: "Cred", identifier: "cred", platform: AtsPlatform.GREENHOUSE },
  { name: "Groww", identifier: "groww", platform: AtsPlatform.GREENHOUSE },
  { name: "Meesho", identifier: "meesho", platform: AtsPlatform.GREENHOUSE },
  { name: "Freshworks", identifier: "freshworks", platform: AtsPlatform.GREENHOUSE },
  { name: "InMobi", identifier: "inmobi", platform: AtsPlatform.GREENHOUSE },
  { name: "Ola", identifier: "ola", platform: AtsPlatform.GREENHOUSE },
  { name: "BrowserStack", identifier: "browserstack", platform: AtsPlatform.GREENHOUSE },
  { name: "Chargebee", identifier: "chargebee", platform: AtsPlatform.GREENHOUSE },
  { name: "Postman", identifier: "postman", platform: AtsPlatform.GREENHOUSE },
  { name: "Zerodha", identifier: "zerodha", platform: AtsPlatform.GREENHOUSE },

  // LEVER
  { name: "Figma", identifier: "figma", platform: AtsPlatform.LEVER },
  { name: "Netflix", identifier: "netflix", platform: AtsPlatform.LEVER },
  { name: "Atlassian", identifier: "atlassian", platform: AtsPlatform.LEVER },
  { name: "Canva", identifier: "canva", platform: AtsPlatform.LEVER },
  { name: "Palantir", identifier: "palantir", platform: AtsPlatform.LEVER },
  { name: "Udacity", identifier: "udacity", platform: AtsPlatform.LEVER },
  { name: "Shopify", identifier: "shopify", platform: AtsPlatform.LEVER },
  { name: "KPMG", identifier: "kpmg", platform: AtsPlatform.LEVER },
  { name: "Docusign", identifier: "docusign", platform: AtsPlatform.LEVER },
  { name: "Evernote", identifier: "evernote", platform: AtsPlatform.LEVER },
  { name: "Yelp", identifier: "yelp", platform: AtsPlatform.LEVER },
  { name: "Box", identifier: "box", platform: AtsPlatform.LEVER },
  { name: "Eventbrite", identifier: "eventbrite", platform: AtsPlatform.LEVER },
  { name: "Zepto", identifier: "zepto", platform: AtsPlatform.LEVER },

  // ASHBY
  { name: "Notion", identifier: "notion", platform: AtsPlatform.ASHBY },
  { name: "Deel", identifier: "deel", platform: AtsPlatform.ASHBY },
  { name: "Rippling", identifier: "rippling", platform: AtsPlatform.ASHBY },
  { name: "Linear", identifier: "linear", platform: AtsPlatform.ASHBY },
  { name: "Vanta", identifier: "vanta", platform: AtsPlatform.ASHBY },
  { name: "Remote.com", identifier: "remote", platform: AtsPlatform.ASHBY },
];
